spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**


server:
  port: 8788

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    com.example.apigateway.config.JwtFilter: DEBUG
    org.springframework.security: DEBUG